# Generated by Django 3.2 on 2021-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210520_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='codenumber',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password1',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
